# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-14 22:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('borrowed', 'Borrowed'), ('overDue', 'OverDue')], default='available', max_length=120),
        ),
    ]
