# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-14 22:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0002_tool_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='late_fine',
            field=models.IntegerField(default=6, help_text='In us dollars'),
        ),
    ]
